theme: github-pages-minimal
title: Stephan Thies
description: This website is work in progress and currently not up to date

---
  defaults:
    # _docs
    - scope:
        path: ""
        type: main
      values:
        sidebar:
          nav: "main"
  ---  
